services:

  vectordb:
    extends:
      file: compose.yml
      service: vectordb
    ports:
      - 6333:6333
      - 6334:6334

  api:
    extends:
      file: compose.yml
      service: api
    ports:
      - 8000:80
    volumes:
      - ./src:/app/src
      - ./packages:/app/packages
      # - ./prestart.sh:/app/prestart.sh
    entrypoint: /start-reload.sh

  # langgraph-redis:
  #   extends:
  #     file: compose.yml
  #     service: langgraph-redis

  # langgraph-postgres:
  #   extends:
  #     file: compose.yml
  #     service: langgraph-postgres
  #   ports:
  #     - 5433:5432

  # langgraph-api:
  #   extends:
  #     file: compose.yml
  #     service: langgraph-api
  #   ports:
  #     - 8123:8000

  # In case you need a GPU-enabled workspace
  # workspace:
  #   image: ghcr.io/vemonet/gpu-workspace:main
  #   # Enable GPUs in this container:
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             capabilities: [gpu]
  #             count: 1
  #   # Shared memory size for the container
  #   shm_size: '8g'
  #   volumes:
  #   - ./:/app
  #   # - /tmp/fastembed_cache/models--qdrant--bge-large-en-v1.5-onnx/:/tmp/fastembed_cache/models--qdrant--bge-large-en-v1.5-onnx/
  #   environment:
  #     TZ: Europe/Amsterdam
