services:

  workspace:
    image: ghcr.io/vemonet/gpu-workspace:main
    # Enable GPUs in this container:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: 1
    # Shared memory size for the container
    shm_size: '16g'
    volumes:
    - ./:/app
    environment:
      TZ: Europe/Amsterdam

  qdrant:
    # https://hub.docker.com/r/qdrant/qdrant/tags
    image: qdrant/qdrant:v1.9.2
    # image: qdrant/qdrant:v1.9.2-unprivileged # Unprivileged don't work when mounting a volume
    restart: unless-stopped
    volumes:
      - ./data/qdrant:/qdrant/storage
      # - ./qdrant_config.yml:/qdrant/config/production.yaml
    environment:
      - QDRANT_ALLOW_RECOVERY_MODE=true
    # ports:
    #   - 6333:6333
    #   - 6334:6334
    # command:
    #   - ./qdrant --config-path /qdrant/config/production.yaml
