name: Tests
on:
  push:
    branches: ["main"]
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:

  tests:
    name: ✅ Run tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        os: ["ubuntu-latest"]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Test with coverage
      run: |
        cd src/sparql-llm
        uv venv --python ${{ matrix.python-version }}
        uv pip install -e .
        uv run pytest
    # Manually creating the venv required because one of the workspace member requires python >=3.12
